const types = {
    GET_MENU_ENTRIES_FULFILLED: { type: '@BAL/GET_MENU_ENTRIES_FULFILLED' },
    GET_MENU_ENTRIES_REJECTED: { type: '@BAL/GET_MENU_ENTRIES_REJECTED' },
    GET_MENU_ENTRIES_PENDING: { type: '@BAL/GET_MENU_ENTRIES_PENDING' },

    GET_FAVORITES_MENU_ENTRIES_FULFILLED: { type: '@BAL/GET_FAVORITES_MENU_ENTRIES_FULFILLED' },
    GET_FAVORITES_MENU_ENTRIES_REJECTED: { type: '@BAL/GET_FAVORITES_MENU_ENTRIES_REJECTED' },
    GET_FAVORITES_MENU_ENTRIES_PENDING: { type: '@BAL/GET_FAVORITES_MENU_ENTRIES_PENDING' },

    FETCH_TRACES_PENDING: { type: '@TPGROUP/FETCH_TRACES_PENDING' },
    FETCH_TRACES_FULFILLED: { type: '@TPGROUP/FETCH_TRACES_FULFILLED' },
    FETCH_TRACES_REJECTED: { type: '@TPGROUP/FETCH_TRACES_REJECTED' },

    FETCH_PS_PENDING: { type: '@TPGROUP/FETCH_PS_PENDING' },
    FETCH_PS_FULFILLED: { type: '@TPGROUP/FETCH_PS_FULFILLED' },
    FETCH_PS_REJECTED: { type: '@TPGROUP/FETCH_PS_REJECTED' },

};
export default types;
