apiVersion: v2
name: onlinestandard-tpgroup-trace-extractor
description: Helm chart for onlinestandard-tpgroup-trace-extractor in tpgroup service.
type: application
appVersion: "${imageTag}"
version: 0.0.0
dependencies:
  - name: helm-chart-beyond-common
    repository: "@beyond"
    version: v14.5.7
