const types = {
    INIT_CONFIGURATION: { type: 'INIT_CONFIGURATION' },
    INIT_CONFIGURATION_FULFILLED: { type: 'INIT_CONFIGURATION_FULFILLED' },
    INIT_CONFIGURATION_PENDING: { type: 'INIT_CONFIGURATION_PENDING' },
    INIT_CONFIGURATION_REJECTED: { type: 'INIT_CONFIGURATION_REJECTED' },
};

export default types;
